### PR TITLE
add .github/workflows/sonarcloud.yml, add sonarqube with properties to build.gradle

### PR DESCRIPTION
**Pull request by jo2**
* use CircleCI for gradle build sonarqube
* submit analyze result to [SonarCloud](https://sonarcloud.io/dashboard?branch=circleci-project-setup&id=adessoAG_coderadar)

### CODE REVIEW

**Comment by KilianKrause** [comment]
Why did you include CircleCI? Does it not work with TavisCI? If we decide to switch to GH Actions (see #358 ) it should work as well, right?

**Comment by jo2** [comment]
GitHub-Actions should also work. As a first try I used CircleCI because it was one of the offered options on SonarCloud. It shouldn't be that much work to use GitHub-Actions instead of CircleCI, I think.

I didn't use Travis because according to the tutorial which was linked on SonarCloud you need to encrypt environment variables manually. To do so you, at least according to this tutorial, have to install ruby on your local system. This is some added work which I didn't want to do and with CircleCI I didn't need to do such a thing.

**Comment by jo2** [comment]
Then I'll change the setup to github pages.

**Comment by maximAtanasov** [comment]
Can this PR be merged?

**Comment by jo2** [comment]
Yeah, this can be merged. I just removed the circle-ci files and it also shouldn't be registered by circle-ci anymore.

**Pull request merged**
