### PR TITLE
Cityview usability improvements

### PR DESCRIPTION
**Pull request by LauchInterceptor**
### Features

- **Element Multiselection**
      Select multiple elements to view their combined metrics in the comparison panel
- **Split view metric hover panels**
      View element metrics of the currently hovered element on both commits simultaneously
- **Changetype Indicators**
      Displays the changetype of a file on top of the element

### CODE REVIEW

**Comment by maximAtanasov** [comment]
What's up with this PR?

**Comment by LauchInterceptor** [comment]
#393 Fixed an issue which rendered me unable to enter the 3D-view. Im looking to finish this pr this week

**Comment by maximAtanasov** [comment]
Unfortunately, when renames have occured between commits, the UI bugs out and no metrics-pop-up/metric-panel is displayed:

Annotation 2020-09-02 092746

Also, you've changed the default selection behaviour to be a double click, could you elaborate why?

**Comment by LauchInterceptor** [comment]
I wanted to enable the user to see the combined metrics of multiple files, hence the single click is now used for selecting but not focusing on multiple elements by holding left shift while clicking.
Though the ability to see combined file metrics is not implemented yet since the pr already contains too many features in my opinion. What are your thoughts?

**Comment by maximAtanasov** [comment]
Ok, this might be a neat feature. I was just initialy confused as to what the selection was supposed to do. Could you open an issue for the aggregation?

**Comment by LauchInterceptor** [comment]
I created an issue #409 as you suggested

**Review by maximAtanasov — APPROVED** [review]

**Pull request merged**
